name: M3U Güncelle

on:
  schedule:
    - cron: '30 */5 * * *'   # Her 5 saatte bir (30. dakikada)
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Repo'yu çek
        uses: actions/checkout@v6
      
      - name: 🐍 Python kur
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      
      - name: 🔄 Playlist'i güncelle
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          KANALLAR: ${{ vars.KANALLAR }}
        run: python update_playlist.py
      
      - name: 📤 Gist'e Yükle (Secret Gist)
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.ytokenred }}
          gist_id: 69356131d65dc88e267300e867641048
          file_path: ytlistem.m3u
          file_type: text
          # description: "YouTube Playlist M3U"  # İstersen aç
